---
title: "Employee Survey Data"
output: html_document
date: "2025-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Employee_Survey_Data <- read.csv("Typical_Employee_Survey_Data.csv")
summary(Employee_Survey_Data)
boxplot(Employee_Survey_Data)
```

```{r}
Employee_Survey_Data$Gender <- as.factor(Employee_Survey_Data$Gender)
```

```{r}
hist(Employee_Survey_Data$Age)
pie(table(Employee_Survey_Data$Gender))
barplot(table(Employee_Survey_Data$JobSatisfaction))
barplot(table(Employee_Survey_Data$ImpJobCharacteristic))
hist(Employee_Survey_Data$YearsWorked)
barplot(table(Employee_Survey_Data$PromotionLikelihood))
barplot(table(Employee_Survey_Data$DecisionAuthority))
barplot(table(Employee_Survey_Data$BudgetAuthority))
barplot(table(Employee_Survey_Data$OrgPride))
barplot(table(Employee_Survey_Data$JobChurn))
barplot(table(Employee_Survey_Data$WorkRelation))
```

```{r}
plot(Employee_Survey_Data$OrgPride, Employee_Survey_Data$JobSatisfaction)
plot(Employee_Survey_Data$YearsWorked, Employee_Survey_Data$DecisionAuthority)
plot(Employee_Survey_Data$YearsWorked, Employee_Survey_Data$PromotionLikelihood)
```

